### ISSUE TITLE
[JOSE] Some math not rendered in module-02-02_Modeling-Exercises.ipynb

### ISSUE THREAD

**Issue by arokem** [shawnrhoads/gu-psyc-347#183]
In [this notebook](https://github.com/shawnrhoads/gu-psyc-347/blob/master/docs/module-02-02_Modeling-Exercises.ipynb) there's some math that doesn't render under the "Finding the Maximum Likelihood Estimator" header.

**Comment by shawnrhoads** [comment]
Hi @arokem,

Thanks for catching this! I did notice the faulty math rendering on my end when you first opened this issue. As I was planning to remedy this today, however, I saw that the rendering seems to work now on [GitHub](https://github.com/shawnrhoads/gu-psyc-347/blob/master/docs/module-02-02_Modeling-Exercises.ipynb) and the [Jupyter Book](https://shawnrhoads.github.io/gu-psyc-347/module-02-02_Modeling-Exercises.html#finding-the-maximum-likelihood-estimator) using both Firefox (v94.0.2 Desktop; v94.1.2 Mobile) and Chrome (v96.0.4664.45 Desktop).

Can you help confirm this on your end? Thanks so much!

**Comment by arokem** [comment]
Confirmed! Must have been some kind of glitch somewhere...
